# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_ocr.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='image_ocr.proto',
  package='ocr',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fimage_ocr.proto\x12\x03ocr\"\x1d\n\x0cOcrCandidate\x12\r\n\x05image\x18\x01 \x01(\x0c\"\x19\n\tOcrResult\x12\x0c\n\x04text\x18\x01 \x01(\t24\n\x03OCR\x12-\n\x06\x44\x65tect\x12\x11.ocr.OcrCandidate\x1a\x0e.ocr.OcrResult\"\x00\x62\x06proto3'
)




_OCRCANDIDATE = _descriptor.Descriptor(
  name='OcrCandidate',
  full_name='ocr.OcrCandidate',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='ocr.OcrCandidate.image', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=53,
)


_OCRRESULT = _descriptor.Descriptor(
  name='OcrResult',
  full_name='ocr.OcrResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='text', full_name='ocr.OcrResult.text', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=80,
)

DESCRIPTOR.message_types_by_name['OcrCandidate'] = _OCRCANDIDATE
DESCRIPTOR.message_types_by_name['OcrResult'] = _OCRRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

OcrCandidate = _reflection.GeneratedProtocolMessageType('OcrCandidate', (_message.Message,), {
  'DESCRIPTOR' : _OCRCANDIDATE,
  '__module__' : 'image_ocr_pb2'
  # @@protoc_insertion_point(class_scope:ocr.OcrCandidate)
  })
_sym_db.RegisterMessage(OcrCandidate)

OcrResult = _reflection.GeneratedProtocolMessageType('OcrResult', (_message.Message,), {
  'DESCRIPTOR' : _OCRRESULT,
  '__module__' : 'image_ocr_pb2'
  # @@protoc_insertion_point(class_scope:ocr.OcrResult)
  })
_sym_db.RegisterMessage(OcrResult)



_OCR = _descriptor.ServiceDescriptor(
  name='OCR',
  full_name='ocr.OCR',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=82,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='Detect',
    full_name='ocr.OCR.Detect',
    index=0,
    containing_service=None,
    input_type=_OCRCANDIDATE,
    output_type=_OCRRESULT,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_OCR)

DESCRIPTOR.services_by_name['OCR'] = _OCR

# @@protoc_insertion_point(module_scope)
