# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_ocr_pb2 as image__ocr__pb2


class OCRStub(object):
    """Service to perform OCR over image.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Detect = channel.unary_unary(
                '/ocr.OCR/Detect',
                request_serializer=image__ocr__pb2.OcrCandidate.SerializeToString,
                response_deserializer=image__ocr__pb2.OcrResult.FromString,
                )


class OCRServicer(object):
    """Service to perform OCR over image.
    """

    def Detect(self, request, context):
        """Determines the text on an input image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OCRServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Detect': grpc.unary_unary_rpc_method_handler(
                    servicer.Detect,
                    request_deserializer=image__ocr__pb2.OcrCandidate.FromString,
                    response_serializer=image__ocr__pb2.OcrResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ocr.OCR', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OCR(object):
    """Service to perform OCR over image.
    """

    @staticmethod
    def Detect(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ocr.OCR/Detect',
            image__ocr__pb2.OcrCandidate.SerializeToString,
            image__ocr__pb2.OcrResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
